# Generated by Django 6.0.3 on 2026-03-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropiedadDestacada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler')], max_length=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='propiedades/')),
                ('habitaciones', models.IntegerField()),
                ('baños', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('cargo', models.CharField(default='Cliente Satisfecho', max_length=100)),
            ],
        ),
    ]
