# Generated by Django 6.0.3 on 2026-03-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_propiedaddestacada_testimonio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropiedadDestacada',
        ),
    ]
