# Generated by Django 6.0.3 on 2026-03-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_delete_propiedaddestacada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Testimonio',
        ),
    ]
